name: "build-frontend"

on:
  push:
    branches: [ master ]

jobs:
  # react build and test
  buildtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm i
    - name: Running Tests
      run: |
        npm run test
    - name: Running Build
      run: |
        npm run build
    - name: Caching dist directory
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: /home/runner/work/asteroid-js/asteroid-js/dist
        if-no-files-found: error
